use_frameworks!
platform : ios, '8.0'
target 'LYProtocolAnimation_Example' do
  pod 'LYProtocolAnimation', :path => '../'

  target 'LYProtocolAnimation_Tests' do
    inherit! :search_paths

    
  end
end
